#!/bin/bash
# RUNME.sh - Start development services template
# Generated by supernal-code package
#
# Part of the ME.sh convention:
#   BUILDME.sh  - Build and setup the project
#   TESTME.sh   - Run the test suite
#   RUNME.sh    - Start development services

set -e

# Configuration
KILL_PORTS=false
SERVICE=""
DEFAULT_PORT=3000

# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Help function
show_help() {
    cat << 'EOF'
RUNME.sh - Start Development Services

Usage: ./RUNME.sh [service] [options]

Services:
  dev           Start development server (default)
  all           Start all available services

Options:
  --port N      Use specific port (default: auto-detect or 3000)
  --kill        Kill processes on conflicting ports before starting
  --help, -h    Show this help message

Examples:
  ./RUNME.sh                    # Start default dev server
  ./RUNME.sh --kill             # Kill port conflicts, then start
  ./RUNME.sh --port 3001        # Start on specific port
  ./RUNME.sh --help             # Show this help

Part of the ME.sh convention:
  BUILDME.sh    Build and setup the project
  TESTME.sh     Run the test suite
  RUNME.sh      Start development services (this script)
EOF
}

# Function to kill process on port
kill_port() {
    local port=$1
    local pid=$(lsof -ti:$port 2>/dev/null)
    if [ ! -z "$pid" ]; then
        log_warning "Killing process on port $port (PID: $pid)"
        kill -9 $pid 2>/dev/null || true
        sleep 1
    fi
}

# Function to check if port is available
check_port() {
    local port=$1
    if lsof -ti:$port > /dev/null 2>&1; then
        return 1
    fi
    return 0
}

# Detect and start appropriate dev server
start_dev() {
    log_info "Starting development server..."
    
    if [ "$KILL_PORTS" = true ]; then
        kill_port $DEFAULT_PORT
    fi
    
    if ! check_port $DEFAULT_PORT; then
        log_error "Port $DEFAULT_PORT is in use. Use --kill to free it."
        return 1
    fi
    
    # Check for node_modules
    if [[ -f "package.json" ]] && [[ ! -d "node_modules" ]]; then
        log_warning "Installing dependencies first..."
        npm install
    fi
    
    # Detect and run appropriate dev command
    if [[ -f "package.json" ]]; then
        if npm run 2>/dev/null | grep -q "dev"; then
            log_success "Starting on http://localhost:$DEFAULT_PORT"
            npm run dev
        elif npm run 2>/dev/null | grep -q "start"; then
            log_success "Starting on http://localhost:$DEFAULT_PORT"
            npm start
        else
            log_error "No dev or start script found in package.json"
            return 1
        fi
    elif [[ -f "Makefile" ]] && grep -q "run:" Makefile; then
        log_success "Running make run"
        make run
    else
        log_error "No runnable configuration found"
        return 1
    fi
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --help|-h)
            show_help
            exit 0
            ;;
        --kill|--kill-conflicts)
            KILL_PORTS=true
            shift
            ;;
        --port)
            DEFAULT_PORT="$2"
            shift 2
            ;;
        dev|all)
            SERVICE="$1"
            shift
            ;;
        *)
            log_error "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Main execution
echo ""
log_info "RUNME.sh - Development Server"
echo ""

case "${SERVICE:-dev}" in
    dev|all)
        start_dev
        ;;
    *)
        log_error "Unknown service: $SERVICE"
        show_help
        exit 1
        ;;
esac

