import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Simplified sidebar configuration for Supernal Coding CLI documentation
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'CLI Commands',
      link: {
        type: 'generated-index',
        title: 'CLI Commands',
        description: 'All Supernal Coding CLI commands'
      },
      items: [{ type: 'autogenerated', dirName: 'cli-commands' }]
    }
  ]
};

export default sidebars;
