import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Simplified sidebar configuration for Supernal Coding CLI documentation
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // Introduction - Value prop and overview
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    // Getting Started - Separate top-level section for new users
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'guides/getting-started/index',
      },
      items: [{ type: 'autogenerated', dirName: 'guides/getting-started' }]
    },
    // Guides - How-to guides for specific tasks
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Guides',
        description: 'How-to guides for specific tasks and workflows'
      },
      items: [
        { type: 'autogenerated', dirName: 'guides/dashboard' },
        { type: 'autogenerated', dirName: 'guides/deployment' },
        'guides/ai-prompting-guide',
        'guides/git-hooks-configuration',
        'guides/configuration-management',
        'guides/understanding-phases',
        'guides/workflow-state-diagrams',
        'guides/gpg-signed-commits-setup',
        'guides/CLI_USAGE_GUIDE',
        'guides/GIT_HOOKS_COMPREHENSIVE_GUIDE',
        'guides/BUILDME_TESTME_STANDARDS',
        'guides/USAGE_SHORTCUTS',
        'guides/PRINCIPLES',
      ]
    },
    // CLI Commands - Reference documentation
    {
      type: 'category',
      label: 'CLI Commands',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'CLI Commands',
        description: 'Complete reference for all Supernal Coding CLI commands'
      },
      items: [{ type: 'autogenerated', dirName: 'cli-commands' }]
    },
    // Compliance - Templates for regulatory frameworks
    {
      type: 'category',
      label: 'Compliance Frameworks',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Compliance Frameworks',
        description: 'Ready-to-use templates for HIPAA, SOC2, ISO 27001, GDPR, FDA, and more'
      },
      items: [{ type: 'autogenerated', dirName: 'compliance' }]
    },
    // SOPs - Standard Operating Procedures
    {
      type: 'category',
      label: 'Standard Operating Procedures',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'SOPs',
        description: '12-phase AI-accelerated development workflow'
      },
      items: [{ type: 'autogenerated', dirName: 'sops' }]
    }
  ]
};

export default sidebars;
