import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for Supernal Coding documentation
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'guides/getting-started/intro',
    {
      type: 'category',
      label: '🚀 Getting Started',
      items: [
        'guides/getting-started/overview/what-is-supernal-coding',
        'guides/getting-started/index'
      ]
    },
    {
      type: 'category',
      label: '📋 Standard Operating Procedures',
      link: {
        type: 'doc',
        id: 'workflow/sops/README'
      },
      items: [
        'workflow/sops/SOP-0-overview-complete-workflow',
        'workflow/sops/SOP-0.1-ai-accelerated-workflow-overview',
        {
          type: 'category',
          label: 'AI Workflow Foundations',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'workflow/sops/general' }]
        },
        {
          type: 'category',
          label: 'Phase-Specific SOPs',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'Phase 1: Discovery',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-1-discovery'
                }
              ]
            },
            {
              type: 'category',
              label: 'Phase 2: Research',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-2-research'
                }
              ]
            },
            {
              type: 'category',
              label: 'Phase 3: Design',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-3-design'
                }
              ]
            },
            {
              type: 'category',
              label: 'Phase 4: Planning',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-4-planning'
                }
              ]
            },
            {
              type: 'category',
              label: 'Phase 5: Requirements',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-5-requirements'
                }
              ]
            },
            {
              type: 'category',
              label: 'Phase 6: Tests',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-6-tests'
                }
              ]
            },
            {
              type: 'category',
              label: 'Phase 7: Build',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-7-build'
                }
              ]
            },
            {
              type: 'category',
              label: 'Phase 8: Integration',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-8-integration'
                }
              ]
            },
            {
              type: 'category',
              label: 'Phase 9: Milestone',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-9-milestone'
                }
              ]
            },
            {
              type: 'category',
              label: 'Phase 10: Staging',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-10-staging'
                }
              ]
            },
            {
              type: 'category',
              label: 'Phase 11: Production',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-11-production'
                }
              ]
            },
            {
              type: 'category',
              label: 'Phase 12: Operations',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflow/sops/phase-12-operations'
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Tool-Specific SOPs',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'workflow/sops/tools' }]
        }
      ]
    },
    {
      type: 'category',
      label: '📚 Guides',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '⚡ Quick Reference',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/cli-commands'
            },
            'guides/understanding-phases'
          ]
        },
        {
          type: 'category',
          label: '📊 Visual Guides',
          items: [
            'guides/dashboard/dashboard-guide',
            'guides/workflow-state-diagrams'
          ]
        },
        {
          type: 'category',
          label: '🚀 Additional Guides',
          items: [
            'guides/configuration-management',
            'guides/git-hooks-configuration',
            'guides/fixing-broken-links'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: '🏛️ Compliance Frameworks',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'requirements/compliance' }]
    }
  ]
};

export default sidebars;
