#!/usr/bin/env node

/**
 * Validate that all files referenced in sidebars.ts actually exist
 * Run before starting Docusaurus to catch configuration errors
 */

const fs = require('node:fs');
const path = require('node:path');

// Import sidebar config (requires transpiling TS to JS or reading raw)
const sidebarPath = path.join(__dirname, 'sidebars.ts');
const docsPath = path.join(__dirname, '..', 'docs'); // '../docs' as per docusaurus.config.ts

console.log('🔍 Validating documentation structure...\n');
console.log(`Docs path: ${docsPath}`);
console.log(`Sidebar config: ${sidebarPath}\n`);

let errors = 0;

// Extract doc IDs from sidebar config (simple regex for this case)
const sidebarContent = fs.readFileSync(sidebarPath, 'utf8');
const docIdMatches = sidebarContent.match(/'([^']+)'/g);

if (!docIdMatches) {
  console.error('❌ Could not parse sidebar file');
  process.exit(1);
}

const docIds = docIdMatches
  .map((m) => m.replace(/'/g, ''))
  .filter(
    (id) =>
      !id.includes('type') &&
      !id.includes('label') &&
      !id.includes('dirName') &&
      !id.includes('autogenerated') &&
      !id.startsWith('@') && // Exclude TypeScript type annotations
      id.includes('/')
  );

console.log(`Found ${docIds.length} explicit doc references to validate:\n`);

docIds.forEach((docId) => {
  const possiblePaths = [
    path.join(docsPath, `${docId}.md`),
    path.join(docsPath, `${docId}.mdx`),
    path.join(docsPath, docId, 'index.md'),
    path.join(docsPath, docId, 'index.mdx')
  ];

  const exists = possiblePaths.some((p) => fs.existsSync(p));

  if (!exists) {
    console.error(`❌ Missing: ${docId}`);
    console.error(`   Looked in:`);
    possiblePaths.forEach((p) => console.error(`   - ${p}`));
    errors++;
  } else {
    console.log(`✅ ${docId}`);
  }
});

// Check autogenerated directories
const autogenDirs = ['guides/cli-commands', 'requirements/compliance'];

console.log(`\n📁 Checking autogenerated directories:\n`);

autogenDirs.forEach((dirName) => {
  const dirPath = path.join(docsPath, dirName);

  if (!fs.existsSync(dirPath)) {
    console.error(`❌ Directory missing: ${dirName} (${dirPath})`);
    errors++;
  } else {
    const files = fs
      .readdirSync(dirPath)
      .filter((f) => f.endsWith('.md') || f.endsWith('.mdx'));
    console.log(`✅ ${dirName} (${files.length} files)`);
  }
});

console.log(`\n${'='.repeat(60)}`);
if (errors > 0) {
  console.error(`\n❌ Validation failed with ${errors} error(s)`);
  console.error('\nFix these issues before starting Docusaurus.\n');
  process.exit(1);
} else {
  console.log('\n✅ All documentation references are valid!\n');
  process.exit(0);
}
